# fly.toml app configuration file generated for lsacapi on 2023-05-06T12:24:21+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "lsacapi"
primary_region = "ams"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
